#!/usr/bin/env python3
"""
Generate a comprehensive evaluation report from all baseline CSV results.
Reads CSVs generated by compare_virus_trees.py and run_esm2_eval.py,
merges paired results, computes statistics, and outputs a markdown report.

Usage:
  python generate_report.py --output-dir eval_preds [--output-md eval_preds/report.md]
"""
import sys
import os
import csv
import argparse
import math
import random

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def read_csv(csv_path):
    """Read a results CSV and return list of (vid, model, norm_rf)."""
    rows = []
    with open(csv_path) as f:
        reader = csv.reader(f)
        header = next(reader, None)  # skip header
        for row in reader:
            if len(row) >= 5:
                vid = row[0]
                model = row[1]
                try:
                    norm_rf = float(row[4])
                except ValueError:
                    continue
                rows.append((vid, model, norm_rf))
    return rows


def bootstrap_ci(values, n_resamples=10000, ci=0.95):
    n = len(values)
    if n == 0:
        return 0, 0, 0
    means = []
    for _ in range(n_resamples):
        sample = [random.choice(values) for _ in range(n)]
        means.append(sum(sample) / n)
    means.sort()
    lower_tail = (1.0 - ci) / 2.0
    lower_idx = int(lower_tail * n_resamples)
    upper_idx = int((1.0 - lower_tail) * n_resamples) - 1
    return sum(values) / n, means[lower_idx], means[upper_idx]


def paired_wilcoxon(x, y):
    n = len(x)
    if n != len(y) or n == 0:
        return None, None
    diffs = [x[i] - y[i] for i in range(n)]
    nonzero = [abs(d) for d in diffs if d != 0]
    signs = [1 if d > 0 else -1 for d in diffs if d != 0]
    n_nonzero = len(nonzero)
    if n_nonzero == 0:
        return 0.0, 1.0
    sorted_pairs = sorted(zip(nonzero, signs))
    ranks = []
    i = 0
    while i < n_nonzero:
        j = i
        while j < n_nonzero and sorted_pairs[j][0] == sorted_pairs[i][0]:
            j += 1
        avg_rank = (i + j - 1) / 2.0 + 1
        for k in range(i, j):
            ranks.append(avg_rank)
        i = j
    W = sum(r * s for r, (_, s) in zip(ranks, sorted_pairs))
    mu = n_nonzero * (n_nonzero + 1) / 4.0
    sigma = math.sqrt(n_nonzero * (n_nonzero + 1) * (2 * n_nonzero + 1) / 24.0)
    z = (W - mu) / sigma if sigma > 0 else 0
    p = 2 * (1 - 0.5 * (1 + math.erf(abs(z) / math.sqrt(2))))
    return W, p


def cohens_d(x, y):
    n = len(x)
    if n != len(y) or n < 2:
        return None
    diffs = [x[i] - y[i] for i in range(n)]
    mean_diff = sum(diffs) / n
    var_diff = sum((d - mean_diff) ** 2 for d in diffs) / (n - 1)
    if var_diff == 0:
        return 0.0
    return mean_diff / math.sqrt(var_diff)


def summarize_model(rows, model_name):
    """Compute summary statistics for a model."""
    values = [r[2] for r in rows if r[1] == model_name]
    n = len(values)
    if n == 0:
        return None

    sorted_vals = sorted(values)
    mean_val = sum(values) / n
    std_val = (sum((x - mean_val) ** 2 for x in values) / n) ** 0.5
    _, ci_lo, ci_hi = bootstrap_ci(values)

    perfect = sum(1 for v in values if v == 0.0)
    worst = sum(1 for v in values if v >= 0.98)

    dist_bins = {}
    for lo, hi in [(0, 0.2), (0.2, 0.4), (0.4, 0.6), (0.6, 0.8), (0.8, 1.0)]:
        cnt = sum(1 for v in values if lo <= v < hi)
        dist_bins[f"[{lo:.1f}, {hi:.1f})"] = cnt

    return {
        "n": n,
        "mean": mean_val,
        "median": sorted_vals[n // 2],
        "std": std_val,
        "ci_lo": ci_lo,
        "ci_hi": ci_hi,
        "perfect_n": perfect,
        "perfect_pct": perfect / n * 100,
        "worst_n": worst,
        "worst_pct": worst / n * 100,
        "distribution": dist_bins,
        "values": values,
    }


def paired_comparison(rows_a, rows_b, name_a, name_b):
    """Paired comparison between two models on common families."""
    a_dict = {r[0]: r[2] for r in rows_a}
    b_dict = {r[0]: r[2] for r in rows_b}
    common = sorted(set(a_dict.keys()) & set(b_dict.keys()))
    if len(common) == 0:
        return None

    x = [a_dict[v] for v in common]
    y = [b_dict[v] for v in common]
    n = len(common)
    mean_diff = (sum(x) - sum(y)) / n

    W, p = paired_wilcoxon(x, y)
    d = cohens_d(x, y)

    sig = "YES (p<0.05)" if p is not None and p < 0.05 else "NO (p>=0.05)"
    d_label = 'large' if abs(d) > 0.8 else 'medium' if abs(d) > 0.5 else 'small' if abs(d) > 0.2 else 'negligible'

    return {
        "n_paired": n,
        "mean_a": sum(x) / n,
        "mean_b": sum(y) / n,
        "mean_diff": mean_diff,
        "wilcoxon_W": W,
        "p_value": p,
        "significant": sig,
        "cohens_d": d,
        "d_label": d_label,
    }


def generate_markdown_report(all_rows, output_path):
    """Generate a comprehensive markdown report."""
    models = sorted(set(r[1] for r in all_rows))

    lines = []
    lines.append("# PHYLA Virus Phylogeny Evaluation — Comprehensive Report")
    lines.append("")
    lines.append(f"**Generated:** {os.popen('date').read().strip()}")
    lines.append(f"**Total evaluable families:** {len(set(r[0] for r in all_rows))}")
    lines.append("")

    # --- Summary Table ---
    lines.append("## 1. Summary: Multi-Baseline Comparison")
    lines.append("")
    lines.append("| Baseline | Families | Avg normRF | [95% CI] | Median | Perfect% | Worst% |")
    lines.append("|----------|:--------:|:----------:|:--------:|:------:|:--------:|:-----:|")

    summaries = {}
    for model in models:
        s = summarize_model(all_rows, model)
        summaries[model] = s
        if s:
            lines.append(
                f"| **{model}** | {s['n']} | {s['mean']:.4f} "
                f"| [{s['ci_lo']:.4f}, {s['ci_hi']:.4f}] "
                f"| {s['median']:.4f} | {s['perfect_pct']:.1f}% | {s['worst_pct']:.1f}% |"
            )
    lines.append("")

    # --- Distribution ---
    lines.append("## 2. Distribution of normRF")
    lines.append("")
    bins = ["[0.0, 0.2)", "[0.2, 0.4)", "[0.4, 0.6)", "[0.6, 0.8)", "[0.8, 1.0)"]
    header = "| Range | " + " | ".join(f"**{m}**" for m in models) + " |"
    lines.append(header)
    lines.append("|" + "|".join(":--:" for _ in range(len(models) + 1)) + "|")
    for b in bins:
        row = f"| {b} |"
        for m in models:
            s = summaries.get(m)
            if s:
                cnt = s["distribution"].get(b, 0)
                pct = cnt / s["n"] * 100 if s["n"] > 0 else 0
                row += f" {cnt} ({pct:.1f}%) |"
            else:
                row += " — |"
        lines.append(row)
    lines.append("")

    # --- Paired Comparisons ---
    lines.append("## 3. Paired Statistical Comparisons")
    lines.append("")
    lines.append("| Comparison | n | Mean Diff | Cohen's d | Wilcoxon p | Significant? |")
    lines.append("|------------|:--:|:---------:|:---------:|:----------:|:------------:|")

    model_rows = {}
    for r in all_rows:
        model_rows.setdefault(r[1], []).append(r)

    for i in range(len(models)):
        for j in range(i + 1, len(models)):
            a, b = models[i], models[j]
            if a in model_rows and b in model_rows:
                pc = paired_comparison(model_rows[a], model_rows[b], a, b)
                if pc:
                    lines.append(
                        f"| {a} vs {b} | {pc['n_paired']} | "
                        f"{pc['mean_diff']:+.4f} | {pc['cohens_d']:.4f} ({pc['d_label']}) | "
                        f"{pc['p_value']:.2e} | {pc['significant']} |"
                    )
    lines.append("")

    # --- Interpretation ---
    lines.append("## 4. Interpretation Guide")
    lines.append("")
    lines.append("### How to read this report")
    lines.append("")
    lines.append("- **normRF = 0.0**: Tree topologies are identical (perfect match)")
    lines.append("- **normRF = 1.0**: No shared bipartitions (completely different)")
    lines.append("- **Random baseline**: Should always be 1.0 — validates the metric")
    lines.append("- **Cohen's d**: 0.2=small, 0.5=medium, 0.8=large effect")
    lines.append("- **Wilcoxon p < 0.05**: Statistically significant difference")
    lines.append("")
    lines.append("### Caveats (READ BEFORE INTERPRETING)")
    lines.append("")
    lines.append("1. **No ground truth**: The 'reference' is FastTree (approximate ML), not expert-curated trees.")
    lines.append("   Results measure agreement-with-FastTree, not absolute phylogenetic accuracy.")
    lines.append("2. **Input format asymmetry**: Hamming and SeqIdentity use MSA (aligned sequences) while")
    lines.append("   PHYLA and ESM2 use FAA (unaligned). MSA-based methods share input format with FastTree,")
    lines.append("   giving them a systematic advantage in this comparison.")
    lines.append("3. **Domain mismatch**: PHYLA is trained on TreeFam (cellular proteins), tested on VOGDB (viral).")
    lines.append("4. **PHYLA and ESM2 are the only fair comparison**: Both use FAA → embedding → NJ.")
    lines.append("5. **ESM2 was not trained for phylogeny**: Unlike PHYLA which was explicitly trained to predict")
    lines.append("   phylogenetic distances, ESM2 is a general-purpose protein language model.")
    lines.append("")

    # Write
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Report saved: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate evaluation report from CSV results")
    parser.add_argument("--csv-dir", default="eval_preds", help="Directory containing result CSVs")
    parser.add_argument("--csv-pattern", default="virus_*_vs_fasttree.csv", help="Glob pattern for CSVs")
    parser.add_argument("--output-md", default="eval_preds/evaluation_report.md", help="Output markdown path")
    args = parser.parse_args()

    csv_dir = os.path.join(SCRIPT_DIR, args.csv_dir)
    csv_pattern = args.csv_pattern
    import glob
    csv_files = sorted(glob.glob(os.path.join(csv_dir, csv_pattern)))
    if not csv_files:
        print(f"No CSV files found in {csv_dir}/{csv_pattern}")
        return

    print(f"Found {len(csv_files)} CSV files:")
    for f in csv_files:
        print(f"  {os.path.basename(f)}")

    all_rows = []
    for f in csv_files:
        rows = read_csv(f)
        print(f"  Loaded {len(rows)} rows from {os.path.basename(f)}")
        all_rows.extend(rows)

    if not all_rows:
        print("No data loaded!")
        return

    model_counts = {}
    for r in all_rows:
        model_counts[r[1]] = model_counts.get(r[1], 0) + 1
    print(f"\nModels found: {dict(sorted(model_counts.items()))}")

    output_path = os.path.join(SCRIPT_DIR, args.output_md)
    generate_markdown_report(all_rows, output_path)


if __name__ == "__main__":
    main()
